// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for `src/printing_ffi.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class PrintingFfiBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  PrintingFfiBindings(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  PrintingFfiBindings.fromLookup(ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup) : _lookup = lookup;

  int sum(
    int a,
    int b,
  ) {
    return _sum(
      a,
      b,
    );
  }

  late final _sumPtr = _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('sum');
  late final _sum = _sumPtr.asFunction<int Function(int, int)>();

  int sum_long_running(
    int a,
    int b,
  ) {
    return _sum_long_running(
      a,
      b,
    );
  }

  late final _sum_long_runningPtr = _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('sum_long_running');
  late final _sum_long_running = _sum_long_runningPtr.asFunction<int Function(int, int)>();

  ffi.Pointer<PrinterList> get_printers() {
    return _get_printers();
  }

  late final _get_printersPtr = _lookup<ffi.NativeFunction<ffi.Pointer<PrinterList> Function()>>('get_printers');
  late final _get_printers = _get_printersPtr.asFunction<ffi.Pointer<PrinterList> Function()>();

  void free_printer_list(
    ffi.Pointer<PrinterList> printer_list,
  ) {
    return _free_printer_list(
      printer_list,
    );
  }

  late final _free_printer_listPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<PrinterList>)>>('free_printer_list');
  late final _free_printer_list = _free_printer_listPtr.asFunction<void Function(ffi.Pointer<PrinterList>)>();

  ffi.Pointer<PrinterInfo> get_default_printer() {
    return _get_default_printer();
  }

  late final _get_default_printerPtr = _lookup<ffi.NativeFunction<ffi.Pointer<PrinterInfo> Function()>>('get_default_printer');
  late final _get_default_printer = _get_default_printerPtr.asFunction<ffi.Pointer<PrinterInfo> Function()>();

  void free_printer_info(
    ffi.Pointer<PrinterInfo> printer_info,
  ) {
    return _free_printer_info(
      printer_info,
    );
  }

  late final _free_printer_infoPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<PrinterInfo>)>>('free_printer_info');
  late final _free_printer_info = _free_printer_infoPtr.asFunction<void Function(ffi.Pointer<PrinterInfo>)>();

  int open_printer_properties(
    ffi.Pointer<ffi.Char> printer_name,
    int hwnd,
  ) {
    return _open_printer_properties(
      printer_name,
      hwnd,
    );
  }

  late final _open_printer_propertiesPtr = _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.IntPtr)>>('open_printer_properties');
  late final _open_printer_properties = _open_printer_propertiesPtr.asFunction<int Function(ffi.Pointer<ffi.Char>, int)>();

  bool raw_data_to_printer(
    ffi.Pointer<ffi.Char> printer_name,
    ffi.Pointer<ffi.Uint8> data,
    int length,
    ffi.Pointer<ffi.Char> doc_name,
    int num_options,
    ffi.Pointer<ffi.Pointer<ffi.Char>> option_keys,
    ffi.Pointer<ffi.Pointer<ffi.Char>> option_values,
  ) {
    return _raw_data_to_printer(
      printer_name,
      data,
      length,
      doc_name,
      num_options,
      option_keys,
      option_values,
    );
  }

  late final _raw_data_to_printerPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Uint8>, ffi.Int, ffi.Pointer<ffi.Char>, ffi.Int, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>>(
    'raw_data_to_printer',
  );
  late final _raw_data_to_printer = _raw_data_to_printerPtr.asFunction<bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Uint8>, int, ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  bool print_pdf(
    ffi.Pointer<ffi.Char> printer_name,
    ffi.Pointer<ffi.Char> pdf_file_path,
    ffi.Pointer<ffi.Char> doc_name,
    int scaling_mode,
    int copies,
    ffi.Pointer<ffi.Char> page_range,
    int num_options,
    ffi.Pointer<ffi.Pointer<ffi.Char>> option_keys,
    ffi.Pointer<ffi.Pointer<ffi.Char>> option_values,
    ffi.Pointer<ffi.Char> alignment,
  ) {
    return _print_pdf(
      printer_name,
      pdf_file_path,
      doc_name,
      scaling_mode,
      copies,
      page_range,
      num_options,
      option_keys,
      option_values,
      alignment,
    );
  }

  late final _print_pdfPtr =
      _lookup<
        ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int, ffi.Int, ffi.Pointer<ffi.Char>, ffi.Int, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Char>)>
      >('print_pdf');
  late final _print_pdf = _print_pdfPtr
      .asFunction<bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int, int, ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<JobList> get_print_jobs(
    ffi.Pointer<ffi.Char> printer_name,
  ) {
    return _get_print_jobs(
      printer_name,
    );
  }

  late final _get_print_jobsPtr = _lookup<ffi.NativeFunction<ffi.Pointer<JobList> Function(ffi.Pointer<ffi.Char>)>>('get_print_jobs');
  late final _get_print_jobs = _get_print_jobsPtr.asFunction<ffi.Pointer<JobList> Function(ffi.Pointer<ffi.Char>)>();

  void free_job_list(
    ffi.Pointer<JobList> job_list,
  ) {
    return _free_job_list(
      job_list,
    );
  }

  late final _free_job_listPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<JobList>)>>('free_job_list');
  late final _free_job_list = _free_job_listPtr.asFunction<void Function(ffi.Pointer<JobList>)>();

  bool pause_print_job(
    ffi.Pointer<ffi.Char> printer_name,
    int job_id,
  ) {
    return _pause_print_job(
      printer_name,
      job_id,
    );
  }

  late final _pause_print_jobPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>, ffi.Uint32)>>('pause_print_job');
  late final _pause_print_job = _pause_print_jobPtr.asFunction<bool Function(ffi.Pointer<ffi.Char>, int)>();

  bool resume_print_job(
    ffi.Pointer<ffi.Char> printer_name,
    int job_id,
  ) {
    return _resume_print_job(
      printer_name,
      job_id,
    );
  }

  late final _resume_print_jobPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>, ffi.Uint32)>>('resume_print_job');
  late final _resume_print_job = _resume_print_jobPtr.asFunction<bool Function(ffi.Pointer<ffi.Char>, int)>();

  bool cancel_print_job(
    ffi.Pointer<ffi.Char> printer_name,
    int job_id,
  ) {
    return _cancel_print_job(
      printer_name,
      job_id,
    );
  }

  late final _cancel_print_jobPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>, ffi.Uint32)>>('cancel_print_job');
  late final _cancel_print_job = _cancel_print_jobPtr.asFunction<bool Function(ffi.Pointer<ffi.Char>, int)>();

  ffi.Pointer<CupsOptionList> get_supported_cups_options(
    ffi.Pointer<ffi.Char> printer_name,
  ) {
    return _get_supported_cups_options(
      printer_name,
    );
  }

  late final _get_supported_cups_optionsPtr = _lookup<ffi.NativeFunction<ffi.Pointer<CupsOptionList> Function(ffi.Pointer<ffi.Char>)>>('get_supported_cups_options');
  late final _get_supported_cups_options = _get_supported_cups_optionsPtr.asFunction<ffi.Pointer<CupsOptionList> Function(ffi.Pointer<ffi.Char>)>();

  void free_cups_option_list(
    ffi.Pointer<CupsOptionList> option_list,
  ) {
    return _free_cups_option_list(
      option_list,
    );
  }

  late final _free_cups_option_listPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<CupsOptionList>)>>('free_cups_option_list');
  late final _free_cups_option_list = _free_cups_option_listPtr.asFunction<void Function(ffi.Pointer<CupsOptionList>)>();

  ffi.Pointer<WindowsPrinterCapabilities> get_windows_printer_capabilities(
    ffi.Pointer<ffi.Char> printer_name,
  ) {
    return _get_windows_printer_capabilities(
      printer_name,
    );
  }

  late final _get_windows_printer_capabilitiesPtr = _lookup<ffi.NativeFunction<ffi.Pointer<WindowsPrinterCapabilities> Function(ffi.Pointer<ffi.Char>)>>('get_windows_printer_capabilities');
  late final _get_windows_printer_capabilities = _get_windows_printer_capabilitiesPtr.asFunction<ffi.Pointer<WindowsPrinterCapabilities> Function(ffi.Pointer<ffi.Char>)>();

  void free_windows_printer_capabilities(
    ffi.Pointer<WindowsPrinterCapabilities> capabilities,
  ) {
    return _free_windows_printer_capabilities(
      capabilities,
    );
  }

  late final _free_windows_printer_capabilitiesPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<WindowsPrinterCapabilities>)>>('free_windows_printer_capabilities');
  late final _free_windows_printer_capabilities = _free_windows_printer_capabilitiesPtr.asFunction<void Function(ffi.Pointer<WindowsPrinterCapabilities>)>();

  ffi.Pointer<ffi.Char> get_last_error() {
    return _get_last_error();
  }

  late final _get_last_errorPtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>('get_last_error');
  late final _get_last_error = _get_last_errorPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// --- Android: bundled cupsd scheduler (runs inside the app sandbox, app uid) ---
  /// These are no-ops / return errors on non-Android platforms.
  ///
  /// start_cups_server: boots the bundled cupsd from the app sandbox. It creates
  /// the runtime dirs + config under `server_root`, builds the ServerBin symlink
  /// farm pointing at the extracted lib*.so executables in `native_lib_dir`,
  /// forks+execs `native_lib_dir/libcupsd.so`, waits until it answers IPP, then
  /// points the libcups client at it (cupsSetServer 127.0.0.1:<port>).
  /// server_root:    app-writable dir for config/spool/logs/state (e.g. filesDir/cups).
  /// native_lib_dir: applicationInfo.nativeLibraryDir (where the lib*.so live).
  /// data_dir:       dir containing share/cups/{mime,data,templates} extracted from assets.
  /// doc_root:       DocumentRoot for the web interface (static index.html/css/images
  /// extracted from assets). May be NULL/"" to disable the web UI.
  /// Returns the chosen localhost port (>0) on success, or <0 on error
  /// (get_last_error has details).
  int start_cups_server(
    ffi.Pointer<ffi.Char> server_root,
    ffi.Pointer<ffi.Char> native_lib_dir,
    ffi.Pointer<ffi.Char> data_dir,
    ffi.Pointer<ffi.Char> doc_root,
  ) {
    return _start_cups_server(
      server_root,
      native_lib_dir,
      data_dir,
      doc_root,
    );
  }

  late final _start_cups_serverPtr = _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('start_cups_server');
  late final _start_cups_server = _start_cups_serverPtr.asFunction<int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// stop_cups_server: terminates the cupsd child started by start_cups_server.
  void stop_cups_server() {
    return _stop_cups_server();
  }

  late final _stop_cups_serverPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>('stop_cups_server');
  late final _stop_cups_server = _stop_cups_serverPtr.asFunction<void Function()>();

  /// --- Android: USB file-descriptor delivery server (for the bundled Gutenprint
  /// DNP dye-sub backend) ---
  ///
  /// The whole Flutter app (Dart + this C FFI + Kotlin) runs in ONE process, and
  /// cupsd + its backends are children forked from it (start_cups_server). So a
  /// USB fd opened by the app (Kotlin UsbDeviceConnection.getFileDescriptor()) is
  /// valid in the app process, and this C code can hand it to the backend child
  /// over an AF_UNIX socket via SCM_RIGHTS.
  ///
  /// The patched DNP backend (backend_common.c, #ifdef __ANDROID__) reads the env
  /// var PRINTING_FFI_USB_FD_SOCK (a FILESYSTEM AF_UNIX socket path — the same one
  /// start_cups_server wires via a `SetEnv` in cups-files.conf), connects at JOB
  /// DISPATCH, recvmsg's ONE data byte + a SCM_RIGHTS cmsg carrying a single USB
  /// fd (CMSG_LEN(sizeof(int))), then libusb_set_option(NO_DEVICE_DISCOVERY) +
  /// libusb_wrap_sys_device(fd). libusb OWNS the wrapped fd and closes it at job
  /// end, so the server sends a dup() of a long-lived fd on EACH connection.
  ///
  /// start_usb_fd_server: unlink+create+bind+listen an AF_UNIX SOCK_STREAM socket
  /// at `sock_path` (use cups_usb_fd_sock_path() / <serverRoot>/usbfd.sock), then
  /// spawn a detached background thread that loops accept() and, for each
  /// connection, sendmsg's one payload byte + a SCM_RIGHTS cmsg carrying
  /// dup(usb_fd). One active server at a time (single printer). Does NOT take
  /// ownership of `usb_fd` (Kotlin/UsbDeviceConnection owns it); it only sends
  /// dups. Returns 0 on success, -1 on failure (get_last_error has details).
  /// No-op returning -1 on non-Android platforms.
  int start_usb_fd_server(
    ffi.Pointer<ffi.Char> sock_path,
    int usb_fd,
  ) {
    return _start_usb_fd_server(
      sock_path,
      usb_fd,
    );
  }

  late final _start_usb_fd_serverPtr = _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Int)>>('start_usb_fd_server');
  late final _start_usb_fd_server = _start_usb_fd_serverPtr.asFunction<int Function(ffi.Pointer<ffi.Char>, int)>();

  /// stop_usb_fd_server: stops the accept thread and closes+unlinks the server
  /// socket. Does NOT close the caller's original usb_fd (owned by Kotlin) — only
  /// the dups the server created. Safe to call when no server is running.
  void stop_usb_fd_server() {
    return _stop_usb_fd_server();
  }

  late final _stop_usb_fd_serverPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>('stop_usb_fd_server');
  late final _stop_usb_fd_server = _stop_usb_fd_serverPtr.asFunction<void Function()>();

  /// cups_usb_fd_sock_path: the canonical AF_UNIX socket path the fd-server binds,
  /// the backend connects to, and the Kotlin layer must pass to
  /// start_usb_fd_server — computed as <server_root>/usbfd.sock from the most
  /// recent start_cups_server call. Returns a pointer to a static buffer, or NULL
  /// if start_cups_server has not run yet (Android). NULL on other platforms.
  ffi.Pointer<ffi.Char> cups_usb_fd_sock_path() {
    return _cups_usb_fd_sock_path();
  }

  late final _cups_usb_fd_sock_pathPtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>('cups_usb_fd_sock_path');
  late final _cups_usb_fd_sock_path = _cups_usb_fd_sock_pathPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// generate_cups_dnp_ppd: (Android) generate — if not already present — a Gutenprint
  /// PPD for a specific DNP/Citizen dye-sub `driver` id (the DnpUsbManager "make"
  /// string, e.g. "dnp-dsrx1", "dnp-ds620"; matches src/xml/printers/dyesub.xml
  /// <printer driver="..."/>) and return its ABSOLUTE on-device path. Pass that path
  /// straight to add_cups_printer so it uploads the PPD file directly (no cups-driverd).
  /// Requires start_cups_server to have run. Returns a pointer to a static buffer, or
  /// NULL on failure (get_last_error). NULL / unsupported on non-Android platforms.
  ffi.Pointer<ffi.Char> generate_cups_dnp_ppd(
    ffi.Pointer<ffi.Char> driver,
  ) {
    return _generate_cups_dnp_ppd(
      driver,
    );
  }

  late final _generate_cups_dnp_ppdPtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>>('generate_cups_dnp_ppd');
  late final _generate_cups_dnp_ppd = _generate_cups_dnp_ppdPtr.asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  /// add_cups_printer: creates/modifies a printer queue on the (local) CUPS server
  /// via the CUPS-Add-Modify-Printer IPP operation. `ppd_or_model` may be:
  /// - an ABSOLUTE path to a readable .ppd file -> the PPD FILE is uploaded
  /// directly (the `lpadmin -P` mechanism); cups-driverd is NOT invoked;
  /// - a model name such as "raw" (raw queue), "everywhere", or NULL;
  /// - any other ppd-name string, resolved server-side by cups-driverd.
  /// Returns true on success; get_last_error has details on failure.
  bool add_cups_printer(
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> device_uri,
    ffi.Pointer<ffi.Char> ppd_or_model,
  ) {
    return _add_cups_printer(
      name,
      device_uri,
      ppd_or_model,
    );
  }

  late final _add_cups_printerPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('add_cups_printer');
  late final _add_cups_printer = _add_cups_printerPtr.asFunction<bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// remove_cups_printer: deletes a printer queue on the (local) CUPS server via
  /// the CUPS-Delete-Printer IPP operation. Idempotent: a "not found" result is
  /// treated as success (so it is safe to call on USB detach for an already-gone
  /// queue). Returns true on success; get_last_error has details on failure.
  bool remove_cups_printer(
    ffi.Pointer<ffi.Char> name,
  ) {
    return _remove_cups_printer(
      name,
    );
  }

  late final _remove_cups_printerPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>)>>('remove_cups_printer');
  late final _remove_cups_printer = _remove_cups_printerPtr.asFunction<bool Function(ffi.Pointer<ffi.Char>)>();

  /// Functions that submit a job and return a job ID for status tracking.
  int submit_raw_data_job(
    ffi.Pointer<ffi.Char> printer_name,
    ffi.Pointer<ffi.Uint8> data,
    int length,
    ffi.Pointer<ffi.Char> doc_name,
    int num_options,
    ffi.Pointer<ffi.Pointer<ffi.Char>> option_keys,
    ffi.Pointer<ffi.Pointer<ffi.Char>> option_values,
  ) {
    return _submit_raw_data_job(
      printer_name,
      data,
      length,
      doc_name,
      num_options,
      option_keys,
      option_values,
    );
  }

  late final _submit_raw_data_jobPtr = _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Uint8>, ffi.Int, ffi.Pointer<ffi.Char>, ffi.Int, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>>(
    'submit_raw_data_job',
  );
  late final _submit_raw_data_job = _submit_raw_data_jobPtr.asFunction<int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Uint8>, int, ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int submit_pdf_job(
    ffi.Pointer<ffi.Char> printer_name,
    ffi.Pointer<ffi.Char> pdf_file_path,
    ffi.Pointer<ffi.Char> doc_name,
    int scaling_mode,
    int copies,
    ffi.Pointer<ffi.Char> page_range,
    int num_options,
    ffi.Pointer<ffi.Pointer<ffi.Char>> option_keys,
    ffi.Pointer<ffi.Pointer<ffi.Char>> option_values,
    ffi.Pointer<ffi.Char> alignment,
  ) {
    return _submit_pdf_job(
      printer_name,
      pdf_file_path,
      doc_name,
      scaling_mode,
      copies,
      page_range,
      num_options,
      option_keys,
      option_values,
      alignment,
    );
  }

  late final _submit_pdf_jobPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int, ffi.Int, ffi.Pointer<ffi.Char>, ffi.Int, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Char>)>
      >('submit_pdf_job');
  late final _submit_pdf_job = _submit_pdf_jobPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int, int, ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Char>)>();

  /// Submit an arbitrary file (image, PDF, ...) letting CUPS auto-detect the
  /// document format from the file contents. Returns the job id (>0) on success,
  /// 0 on failure. Not supported on Windows. (macOS/Linux/Android via CUPS.)
  int submit_file_job(
    ffi.Pointer<ffi.Char> printer_name,
    ffi.Pointer<ffi.Char> file_path,
    ffi.Pointer<ffi.Char> doc_name,
    int num_options,
    ffi.Pointer<ffi.Pointer<ffi.Char>> option_keys,
    ffi.Pointer<ffi.Pointer<ffi.Char>> option_values,
  ) {
    return _submit_file_job(
      printer_name,
      file_path,
      doc_name,
      num_options,
      option_keys,
      option_values,
    );
  }

  late final _submit_file_jobPtr = _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('submit_file_job');
  late final _submit_file_job = _submit_file_jobPtr.asFunction<int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// Function to initialize the PDFium library. Must be called once on startup on Windows.
  void init_pdfium_library() {
    return _init_pdfium_library();
  }

  late final _init_pdfium_libraryPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>('init_pdfium_library');
  late final _init_pdfium_library = _init_pdfium_libraryPtr.asFunction<void Function()>();

  void shutdown_pdfium_library() {
    return _shutdown_pdfium_library();
  }

  late final _shutdown_pdfium_libraryPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>('shutdown_pdfium_library');
  late final _shutdown_pdfium_library = _shutdown_pdfium_libraryPtr.asFunction<void Function()>();

  bool print_file_with_dialog(
    ffi.Pointer<ffi.Char> file_path,
    ffi.Pointer<ffi.Char> doc_name,
  ) {
    return _print_file_with_dialog(
      file_path,
      doc_name,
    );
  }

  late final _print_file_with_dialogPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('print_file_with_dialog');
  late final _print_file_with_dialog = _print_file_with_dialogPtr.asFunction<bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// CUPS printer control functions (macOS/Linux only)
  bool cups_pause_printer(
    ffi.Pointer<ffi.Char> printer_name,
    ffi.Pointer<ffi.Char> username,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _cups_pause_printer(
      printer_name,
      username,
      password,
    );
  }

  late final _cups_pause_printerPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('cups_pause_printer');
  late final _cups_pause_printer = _cups_pause_printerPtr.asFunction<bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  bool cups_resume_printer(
    ffi.Pointer<ffi.Char> printer_name,
    ffi.Pointer<ffi.Char> username,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _cups_resume_printer(
      printer_name,
      username,
      password,
    );
  }

  late final _cups_resume_printerPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('cups_resume_printer');
  late final _cups_resume_printer = _cups_resume_printerPtr.asFunction<bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  bool cups_enable_printer(
    ffi.Pointer<ffi.Char> printer_name,
    ffi.Pointer<ffi.Char> username,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _cups_enable_printer(
      printer_name,
      username,
      password,
    );
  }

  late final _cups_enable_printerPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('cups_enable_printer');
  late final _cups_enable_printer = _cups_enable_printerPtr.asFunction<bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  bool cups_disable_printer(
    ffi.Pointer<ffi.Char> printer_name,
    ffi.Pointer<ffi.Char> reason,
    ffi.Pointer<ffi.Char> username,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _cups_disable_printer(
      printer_name,
      reason,
      username,
      password,
    );
  }

  late final _cups_disable_printerPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('cups_disable_printer');
  late final _cups_disable_printer = _cups_disable_printerPtr.asFunction<bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  bool cups_accept_jobs(
    ffi.Pointer<ffi.Char> printer_name,
    ffi.Pointer<ffi.Char> username,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _cups_accept_jobs(
      printer_name,
      username,
      password,
    );
  }

  late final _cups_accept_jobsPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('cups_accept_jobs');
  late final _cups_accept_jobs = _cups_accept_jobsPtr.asFunction<bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  bool cups_reject_jobs(
    ffi.Pointer<ffi.Char> printer_name,
    ffi.Pointer<ffi.Char> reason,
    ffi.Pointer<ffi.Char> username,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _cups_reject_jobs(
      printer_name,
      reason,
      username,
      password,
    );
  }

  late final _cups_reject_jobsPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('cups_reject_jobs');
  late final _cups_reject_jobs = _cups_reject_jobsPtr.asFunction<bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// CUPS job control functions (macOS/Linux only)
  bool cups_hold_job(
    ffi.Pointer<ffi.Char> printer_name,
    int job_id,
    ffi.Pointer<ffi.Char> username,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _cups_hold_job(
      printer_name,
      job_id,
      username,
      password,
    );
  }

  late final _cups_hold_jobPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>, ffi.Uint32, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('cups_hold_job');
  late final _cups_hold_job = _cups_hold_jobPtr.asFunction<bool Function(ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  bool cups_release_job(
    ffi.Pointer<ffi.Char> printer_name,
    int job_id,
    ffi.Pointer<ffi.Char> username,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _cups_release_job(
      printer_name,
      job_id,
      username,
      password,
    );
  }

  late final _cups_release_jobPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>, ffi.Uint32, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('cups_release_job');
  late final _cups_release_job = _cups_release_jobPtr.asFunction<bool Function(ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  bool cups_move_job(
    ffi.Pointer<ffi.Char> source_printer,
    int job_id,
    ffi.Pointer<ffi.Char> dest_printer,
    ffi.Pointer<ffi.Char> username,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _cups_move_job(
      source_printer,
      job_id,
      dest_printer,
      username,
      password,
    );
  }

  late final _cups_move_jobPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>, ffi.Uint32, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('cups_move_job');
  late final _cups_move_job = _cups_move_jobPtr.asFunction<bool Function(ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  bool cups_set_job_priority(
    ffi.Pointer<ffi.Char> printer_name,
    int job_id,
    int priority,
    ffi.Pointer<ffi.Char> username,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _cups_set_job_priority(
      printer_name,
      job_id,
      priority,
      username,
      password,
    );
  }

  late final _cups_set_job_priorityPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Char>, ffi.Uint32, ffi.Int, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('cups_set_job_priority');
  late final _cups_set_job_priority = _cups_set_job_priorityPtr.asFunction<bool Function(ffi.Pointer<ffi.Char>, int, int, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// CUPS printer attribute query functions (macOS/Linux/Android only)
  ffi.Pointer<PrinterAttribute> cups_get_printer_attribute(
    ffi.Pointer<ffi.Char> printer_name,
    ffi.Pointer<ffi.Char> attribute_name,
    ffi.Pointer<ffi.Char> username,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _cups_get_printer_attribute(
      printer_name,
      attribute_name,
      username,
      password,
    );
  }

  late final _cups_get_printer_attributePtr = _lookup<ffi.NativeFunction<ffi.Pointer<PrinterAttribute> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('cups_get_printer_attribute');
  late final _cups_get_printer_attribute = _cups_get_printer_attributePtr.asFunction<ffi.Pointer<PrinterAttribute> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<PrinterAttributeList> cups_get_printer_attributes(
    ffi.Pointer<ffi.Char> printer_name,
    ffi.Pointer<ffi.Pointer<ffi.Char>> attribute_names,
    int num_attributes,
    ffi.Pointer<ffi.Char> username,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _cups_get_printer_attributes(
      printer_name,
      attribute_names,
      num_attributes,
      username,
      password,
    );
  }

  late final _cups_get_printer_attributesPtr = _lookup<ffi.NativeFunction<ffi.Pointer<PrinterAttributeList> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Int, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>(
    'cups_get_printer_attributes',
  );
  late final _cups_get_printer_attributes = _cups_get_printer_attributesPtr.asFunction<ffi.Pointer<PrinterAttributeList> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>, int, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// cups_get_all_printer_attributes: query EVERY attribute the printer exposes.
  /// Sends an IPP Get-Printer-Attributes request with requested-attributes="all"
  /// and returns one PrinterAttribute per named attribute in the printer group
  /// (name + value(s), same value formatting as the functions above). Use this to
  /// discover which attribute names a printer supports without knowing them up
  /// front. Returns NULL on error (get_last_error has details). Not on Windows.
  ffi.Pointer<PrinterAttributeList> cups_get_all_printer_attributes(
    ffi.Pointer<ffi.Char> printer_name,
    ffi.Pointer<ffi.Char> username,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _cups_get_all_printer_attributes(
      printer_name,
      username,
      password,
    );
  }

  late final _cups_get_all_printer_attributesPtr = _lookup<ffi.NativeFunction<ffi.Pointer<PrinterAttributeList> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('cups_get_all_printer_attributes');
  late final _cups_get_all_printer_attributes = _cups_get_all_printer_attributesPtr.asFunction<ffi.Pointer<PrinterAttributeList> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  void free_printer_attribute(
    ffi.Pointer<PrinterAttribute> attribute,
  ) {
    return _free_printer_attribute(
      attribute,
    );
  }

  late final _free_printer_attributePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<PrinterAttribute>)>>('free_printer_attribute');
  late final _free_printer_attribute = _free_printer_attributePtr.asFunction<void Function(ffi.Pointer<PrinterAttribute>)>();

  void free_printer_attribute_list(
    ffi.Pointer<PrinterAttributeList> attribute_list,
  ) {
    return _free_printer_attribute_list(
      attribute_list,
    );
  }

  late final _free_printer_attribute_listPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<PrinterAttributeList>)>>('free_printer_attribute_list');
  late final _free_printer_attribute_list = _free_printer_attribute_listPtr.asFunction<void Function(ffi.Pointer<PrinterAttributeList>)>();
}

/// Struct for returning printer information
final class PrinterInfo extends ffi.Struct {
  external ffi.Pointer<ffi.Char> name;

  @ffi.Uint32()
  external int state;

  external ffi.Pointer<ffi.Char> url;

  external ffi.Pointer<ffi.Char> model;

  external ffi.Pointer<ffi.Char> location;

  external ffi.Pointer<ffi.Char> comment;

  @ffi.Bool()
  external bool is_default;

  @ffi.Bool()
  external bool is_available;
}

final class PrinterList extends ffi.Struct {
  @ffi.Int()
  external int count;

  external ffi.Pointer<PrinterInfo> printers;
}

/// Struct for returning print job information
final class JobInfo extends ffi.Struct {
  @ffi.Uint32()
  external int id;

  external ffi.Pointer<ffi.Char> title;

  @ffi.Uint32()
  external int status;
}

final class JobList extends ffi.Struct {
  @ffi.Int()
  external int count;

  external ffi.Pointer<JobInfo> jobs;
}

/// Struct for a single CUPS option choice
final class CupsOptionChoice extends ffi.Struct {
  external ffi.Pointer<ffi.Char> choice;

  external ffi.Pointer<ffi.Char> text;
}

/// Struct for a list of CUPS option choices
final class CupsOptionChoiceList extends ffi.Struct {
  @ffi.Int()
  external int count;

  external ffi.Pointer<CupsOptionChoice> choices;
}

/// Struct for a single CUPS printer option
final class CupsOption extends ffi.Struct {
  external ffi.Pointer<ffi.Char> name;

  external ffi.Pointer<ffi.Char> default_value;

  external CupsOptionChoiceList supported_values;
}

/// Struct for a list of CUPS printer options
final class CupsOptionList extends ffi.Struct {
  @ffi.Int()
  external int count;

  external ffi.Pointer<CupsOption> options;
}

/// Struct for a single Windows paper source (bin)
final class PaperSource extends ffi.Struct {
  @ffi.Short()
  external int id;

  external ffi.Pointer<ffi.Char> name;
}

final class PaperSourceList extends ffi.Struct {
  @ffi.Int()
  external int count;

  external ffi.Pointer<PaperSource> sources;
}

/// Struct for a single Windows media type
final class MediaType extends ffi.Struct {
  @ffi.Short()
  external int id;

  external ffi.Pointer<ffi.Char> name;
}

final class MediaTypeList extends ffi.Struct {
  @ffi.Int()
  external int count;

  external ffi.Pointer<MediaType> types;
}

/// Structs for Windows printer capabilities
final class PaperSize extends ffi.Struct {
  @ffi.Short()
  external int id;

  external ffi.Pointer<ffi.Char> name;

  @ffi.Float()
  external double width_mm;

  @ffi.Float()
  external double height_mm;
}

final class PaperSizeList extends ffi.Struct {
  @ffi.Int()
  external int count;

  external ffi.Pointer<PaperSize> papers;
}

final class Resolution extends ffi.Struct {
  @ffi.Long()
  external int x_dpi;

  @ffi.Long()
  external int y_dpi;
}

final class ResolutionList extends ffi.Struct {
  @ffi.Int()
  external int count;

  external ffi.Pointer<Resolution> resolutions;
}

final class WindowsPrinterCapabilities extends ffi.Struct {
  external PaperSizeList paper_sizes;

  external PaperSourceList paper_sources;

  external ResolutionList resolutions;

  external MediaTypeList media_types;

  /// New fields for color mode and orientation capabilities
  @ffi.Bool()
  external bool is_color_supported;

  @ffi.Bool()
  external bool is_monochrome_supported;

  @ffi.Bool()
  external bool supports_landscape;
}

/// Struct for printer attribute query result
final class PrinterAttribute extends ffi.Struct {
  external ffi.Pointer<ffi.Char> attribute_name;

  external ffi.Pointer<ffi.Char> attribute_value;

  /// For array attributes
  @ffi.Int()
  external int value_count;

  /// For array attributes (NULL if value_count <= 1)
  external ffi.Pointer<ffi.Pointer<ffi.Char>> array_values;
}

final class PrinterAttributeList extends ffi.Struct {
  @ffi.Int()
  external int count;

  external ffi.Pointer<PrinterAttribute> attributes;
}
